# Generated by Django 3.1.5 on 2021-01-10 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
